import { OrderStatus } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { saveProduct, savePromotion, updateOrderStatus } from './actions';

const statuses = Object.values(OrderStatus);
const money = (value:number) => `₦${value.toLocaleString('en-NG')}`;
const dateInput = (date:Date) => new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);

export default async function Admin({searchParams}:{searchParams:Promise<{q?:string;status?:string;from?:string;to?:string}>}){
  const params=await searchParams;
  const status=statuses.includes(params.status as OrderStatus)?params.status as OrderStatus:undefined;
  const createdAt=params.from||params.to?{gte:params.from?new Date(`${params.from}T00:00:00`):undefined,lte:params.to?new Date(`${params.to}T23:59:59.999`):undefined}:undefined;
  const query=params.q?.trim();
  const where={status,createdAt,OR:query?[{fullName:{contains:query,mode:'insensitive' as const}},{phone:{contains:query}},{city:{contains:query,mode:'insensitive' as const}},{state:{contains:query,mode:'insensitive' as const}}]:undefined};
  const [orders,counts,product,promotion]=await Promise.all([
    prisma.order.findMany({where,orderBy:{createdAt:'desc'},take:250}),
    prisma.order.groupBy({by:['status'],_count:true}),
    prisma.product.findUnique({where:{id:'foot-massager'}}),
    prisma.promotion.findUnique({where:{id:'main-promotion'}})
  ]);
  const total=counts.reduce((sum,row)=>sum+row._count,0);
  const exportQuery=new URLSearchParams(Object.entries(params).filter((entry):entry is [string,string]=>Boolean(entry[1]))).toString();
  return <main className="min-h-screen bg-stone-100 dark:bg-[#07110d]"><header className="border-b bg-white dark:border-white/10 dark:bg-white/5"><div className="container-shell flex min-h-16 items-center justify-between gap-4 py-3"><div><p className="font-black">J-Stores Admin</p><p className="text-xs opacity-60">Orders and storefront settings</p></div><form action="/api/admin/logout" method="post"><button className="btn border border-stone-300 py-2 text-sm dark:border-white/15">Sign out</button></form></div></header><div className="container-shell space-y-8 py-8">
    <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-emerald-600">ADMIN DASHBOARD</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Order management</h1></div><a className="btn-primary" href={`/api/admin/orders/export${exportQuery?`?${exportQuery}`:''}`}>Export CSV</a></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-6"><Stat label="All orders" value={total}/>{statuses.map(item=><Stat key={item} label={item} value={counts.find(row=>row.status===item)?._count||0}/>)}</div></section>
    <section className="card overflow-hidden"><form className="grid gap-3 border-b p-4 sm:grid-cols-2 lg:grid-cols-[1fr_180px_160px_160px_auto] dark:border-white/10"><input className="input" name="q" defaultValue={params.q} placeholder="Name, phone, city or state"/><select className="input" name="status" defaultValue={params.status||''}><option value="">All statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><input className="input" type="date" name="from" defaultValue={params.from}/><input className="input" type="date" name="to" defaultValue={params.to}/><button className="btn-primary">Filter</button></form><div className="overflow-x-auto"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide dark:bg-white/5"><tr><th className="p-4">Customer</th><th className="p-4">Delivery</th><th className="p-4">Package</th><th className="p-4">Total</th><th className="p-4">Placed</th><th className="p-4">Status</th></tr></thead><tbody>{orders.map(order=><tr key={order.id} className="border-t align-top dark:border-white/10"><td className="p-4"><strong>{order.fullName}</strong><div>{order.phone}</div>{order.secondPhone&&<div className="opacity-60">{order.secondPhone}</div>}</td><td className="max-w-xs p-4"><div>{order.address}</div><div className="opacity-60">{order.city}, {order.state}{order.landmark?` • ${order.landmark}`:''}</div></td><td className="p-4">{order.quantity} unit{order.quantity>1?'s':''}</td><td className="p-4 font-bold">{money(order.total)}</td><td className="p-4">{order.createdAt.toLocaleDateString('en-NG')}<div className="opacity-60">{order.createdAt.toLocaleTimeString('en-NG',{hour:'2-digit',minute:'2-digit'})}</div></td><td className="p-4"><form action={updateOrderStatus} className="flex gap-2"><input type="hidden" name="id" value={order.id}/><select name="status" defaultValue={order.status} className="rounded-xl border bg-transparent px-3 py-2 dark:border-white/15">{statuses.map(item=><option key={item}>{item}</option>)}</select><button className="rounded-xl bg-stone-900 px-3 py-2 text-white dark:bg-white dark:text-stone-900">Save</button></form></td></tr>)}{!orders.length&&<tr><td className="p-10 text-center opacity-60" colSpan={6}>No orders match these filters.</td></tr>}</tbody></table></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><form action={saveProduct} className="card space-y-4 p-5 sm:p-7"><div><p className="text-sm font-bold text-emerald-600">PRODUCT</p><h2 className="text-2xl font-black">Storefront product</h2></div><label className="block text-sm font-semibold">Name<input className="input mt-1" name="name" defaultValue={product?.name||'Ultimate Foot Massager'} required/></label><label className="block text-sm font-semibold">Description<textarea className="input mt-1 min-h-24" name="description" defaultValue={product?.description||'Deep Shiatsu kneading and soothing heat therapy.'} required/></label><div className="grid grid-cols-2 gap-3">{[1,2,3,5].map(q=><label key={q} className="text-sm font-semibold">{q} unit{q>1?'s':''}<input className="input mt-1" type="number" min="1" name={`price${q}`} defaultValue={product?.[`price${q}` as keyof typeof product] as number||({1:149999,2:294999,3:442999,5:739999} as Record<number,number>)[q]} required/></label>)}</div><label className="flex items-center gap-2"><input type="checkbox" name="active" defaultChecked={product?.active??true}/> Product available for orders</label><button className="btn-primary">Save product</button></form>
    <form action={savePromotion} className="card space-y-4 p-5 sm:p-7"><div><p className="text-sm font-bold text-emerald-600">PROMOTION</p><h2 className="text-2xl font-black">Fixed campaign dates</h2></div><label className="block text-sm font-semibold">Campaign name<input className="input mt-1" name="name" defaultValue={promotion?.name||'Foot Massager Promotion'} required/></label><label className="block text-sm font-semibold">Starts<input className="input mt-1" type="datetime-local" name="startsAt" defaultValue={promotion?dateInput(promotion.startsAt):''} required/></label><label className="block text-sm font-semibold">Ends<input className="input mt-1" type="datetime-local" name="endsAt" defaultValue={promotion?dateInput(promotion.endsAt):''} required/></label><label className="flex items-center gap-2"><input type="checkbox" name="active" defaultChecked={promotion?.active??true}/> Promotion enabled</label><p className="text-sm opacity-60">The promotion is shown only between these fixed dates.</p><button className="btn-primary">Save promotion</button></form></section>
  </div></main>;
}

function Stat({label,value}:{label:string;value:number}){return <div className="card p-4"><p className="text-xs uppercase opacity-60">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
