'use client';
import { useEffect, useRef, useState } from 'react';

const states=['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','FCT Abuja','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara'];

export default function OrderForm({prices:initialPrices={1:149999,2:294999,3:442999,5:739999}}:{prices?:Record<number,number>}){
  const [prices,setPrices]=useState(initialPrices);const [qty,setQty]=useState(1);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const renderedAt=useRef(Date.now());
  useEffect(()=>{fetch('/api/storefront').then(response=>response.ok?response.json():null).then(data=>{if(data?.prices)setPrices(data.prices)}).catch(()=>{})},[]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...data,renderedAt:renderedAt.current,quantity:Number(data.quantity)})});if(!r.ok)throw new Error((await r.json()).error||'Unable to submit order');location.href='/order-success';}catch(err){setError(err instanceof Error?err.message:'Unable to submit order');setLoading(false)}}
  return <form onSubmit={submit} className="card space-y-4 p-5 sm:p-8"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-600">Pay on delivery</p><h3 className="mt-1 text-2xl font-black">Enter your delivery details</h3></div><div className="hidden" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><input className="input" name="fullName" required maxLength={100} placeholder="Full name"/><div className="grid gap-4 sm:grid-cols-2"><input className="input" name="phone" inputMode="tel" required maxLength={20} placeholder="Phone number"/><input className="input" name="secondPhone" inputMode="tel" maxLength={20} placeholder="Second phone number"/></div><div className="grid gap-4 sm:grid-cols-2"><select className="input" name="state" required defaultValue=""><option value="" disabled>Select state</option>{states.map(s=><option key={s}>{s}</option>)}</select><input className="input" name="city" required maxLength={80} placeholder="City"/></div><textarea className="input min-h-24" name="address" required maxLength={300} placeholder="Full delivery address"/><input className="input" name="landmark" maxLength={150} placeholder="Nearest landmark"/><select className="input" name="quantity" value={qty} onChange={e=>setQty(Number(e.target.value))}>{Object.entries(prices).map(([q,p])=><option key={q} value={q}>{q} Foot Massager{Number(q)>1?'s':''} — ₦{p.toLocaleString()}</option>)}</select><div className="rounded-2xl bg-emerald-50 p-4 dark:bg-emerald-500/10"><div className="flex justify-between"><span>Total</span><strong className="text-xl">₦{prices[qty].toLocaleString()}</strong></div><p className="mt-1 text-sm opacity-70">Free nationwide delivery • Pay when it arrives</p></div>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="btn-primary w-full disabled:cursor-not-allowed disabled:opacity-60">{loading?'Submitting…':'Order Now'}</button><p className="text-center text-xs opacity-60">Customer care will call to confirm before dispatch.</p></form>;
}
